/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#dae1ff',
        'surface-container': '#eceef0',
        'inverse-primary': '#b3c5ff',
        'on-tertiary-fixed-variant': '#832600',
        error: '#ba1a1a',
        'surface-container-highest': '#e0e3e5',
        'on-primary-fixed-variant': '#003fa4',
        'on-secondary-fixed': '#001849',
        'on-secondary-fixed-variant': '#284386',
        'on-primary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'secondary-fixed-dim': '#b3c5ff',
        'on-error': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'surface-variant': '#e0e3e5',
        'on-primary-container': '#f8f7ff',
        'tertiary-container': '#cc4204',
        outline: '#727687',
        tertiary: '#a33200',
        'on-primary-fixed': '#001849',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#fff6f4',
        'primary-container': '#0066ff',
        secondary: '#425ca0',
        'on-background': '#191c1e',
        'surface-tint': '#0054d6',
        'on-secondary-container': '#294487',
        'tertiary-fixed-dim': '#ffb59d',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d8dadc',
        'on-surface-variant': '#424656',
        'surface-container-low': '#f2f4f6',
        primary: '#0050cb',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2d3133',
        'secondary-fixed': '#dae1ff',
        'on-tertiary': '#ffffff',
        'outline-variant': '#c2c6d8',
        surface: '#f7f9fb',
        'secondary-container': '#9bb4fe',
        'on-tertiary-fixed': '#390c00',
        'on-error-container': '#93000a',
        background: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#ffdbd0',
        'on-surface': '#191c1e',
        'primary-fixed-dim': '#b3c5ff',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
